name:                compiler-haskell
version:             0.1.0.0

ghc-options: 
- -Wall
- -fno-warn-name-shadowing
- -fno-warn-missing-signatures 
- -fno-warn-unused-do-bind 
- -Werror=incomplete-patterns

dependencies:
- base >= 4.7 && < 5
- parsec
- containers
- either
- text
- hashable
- dlist
- mtl

library:
  source-dirs: src

executables:
  mjc:
    main:                Main.hs
    source-dirs:         app
    dependencies:
    - compiler-haskell

tests:
  unit-tests:
    main:                Spec.hs
    source-dirs:         test/unit
    dependencies:
    - compiler-haskell
    - hspec
  integration-tests:
    main:                Spec.hs
    source-dirs:         test/integration
    dependencies:
    - compiler-haskell
    - hspec
    - directory
    - regex-tdfa
