version: 2
jobs:
  build:
    docker:
      - image: haskell
    steps:
      - checkout
      - restore_cache:
          keys:
            - compiler-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
            - compiler-haskell-v1-{{ checksum "stack.yaml" }}
      - run:
          name: Build
          command: stack --no-terminal build
      - run:
          name: Run tests
          command: stack --no-terminal test
      - save_cache:
          key: compiler-haskell-v1-{{ checksum "stack.yaml" }}-{{ checksum "package.yaml" }}
          paths:
            - "/root/.stack"
            - ".stack-work"